"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
Configured for the IDSC Clinic System midterm mock API with Django REST Framework.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-4uipb%r-hr+7aq+2g7xtu(a6gnf=0s-^ql!b6^=q=vi8g+2kz4'
)

DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,*').split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    # Local apps
    'clinic.apps.ClinicConfig',
    'authentication.apps.AuthenticationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Clinic domain storage mode.
#
# Midterm default: mock/in-memory Clinic business data.
# Finals can introduce a database-backed repository without changing routes.
CLINIC_DATA_BACKEND = os.environ.get(
    'CLINIC_DATA_BACKEND',
    'mock',
)



# Database Configuration
#
# MIDTERM:
# Clinic-owned business/domain resources use CLINIC_DATA_BACKEND="mock"
# and are stored only in the in-memory MockClinicRepository.
#
# SQLite below is framework infrastructure only. Django authentication,
# permissions, groups, sessions, and admin require Django's database layer.
# Clinic HealthRecord, Consultation, HealthStatus, and
# MedicineDispensation endpoints do NOT persist to this database.
#
# FINALS:
# PostgreSQL remains opt-in through DB_ENGINE and the POSTGRES_* variables.

DB_ENGINE = os.environ.get(
    "DB_ENGINE",
    "django.db.backends.sqlite3",
)

if "sqlite3" in DB_ENGINE:
    DB_NAME = os.environ.get(
        "DB_NAME",
        "framework.sqlite3",
    )

    if DB_NAME == ":memory:":
        SQLITE_NAME = DB_NAME
    else:
        sqlite_path = Path(DB_NAME)

        SQLITE_NAME = (
            sqlite_path
            if sqlite_path.is_absolute()
            else BASE_DIR / sqlite_path
        )

    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": SQLITE_NAME,
        }
    }

else:
    DB_NAME = os.environ.get(
        "DB_NAME",
        os.environ.get(
            "POSTGRES_DB",
            "clinic_db",
        ),
    )

    DB_USER = os.environ.get(
        "DB_USER",
        os.environ.get(
            "POSTGRES_USER",
            "postgres",
        ),
    )

    DB_PASSWORD = os.environ.get(
        "DB_PASSWORD",
        os.environ.get(
            "POSTGRES_PASSWORD",
            "postgres",
        ),
    )

    DB_HOST = os.environ.get(
        "DB_HOST",
        os.environ.get(
            "POSTGRES_HOST",
            "localhost",
        ),
    )

    DB_PORT = os.environ.get(
        "DB_PORT",
        os.environ.get(
            "POSTGRES_PORT",
            "5432",
        ),
    )

    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.authentication.ClinicSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'clinic.exceptions.custom_exception_handler',
}


# Spectacular / OpenAPI Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'IDSC Clinic System API',
    'DESCRIPTION': (
        'OpenAPI documentation for the IDSC Clinic System backend. '
        'Provides endpoints for managing student records, health records, clinical consultations, '
        'vital signs, medical histories, and allergies.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',

    # Canonical local development server.
    'SERVERS': [
        {
            'url': 'http://127.0.0.1:8000',
            'description': 'Local Django development server',
        },
    ],

    # Preserve drf-spectacular's enum postprocessing and then
    # normalize project-level OpenAPI documentation metadata.
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'config.schema.postprocess_openapi_metadata',
    ],
}


# CORS Configuration

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# Email
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
