# Generated by Django 6.1.1 on 2026-09-30 07:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, help_text='Opaque student identifier owned by Registrar', max_length=100)),
                ('chief_complaint', models.TextField()),
                ('assessment', models.TextField(blank=True, default='')),
                ('treatment', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultations',
                'ordering': ['-consulted_at', '-consultation_id'],
            },
        ),
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, help_text='Opaque student identifier owned by Registrar', max_length=100)),
                ('status', models.CharField(choices=[('CLEARED', 'Cleared'), ('RESTRICTED', 'Restricted'), ('UNDER_OBSERVATION', 'Under Observation')], max_length=32)),
                ('remarks', models.TextField(blank=True, default='')),
                ('effective_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'health_statuses',
                'ordering': ['-effective_at', '-status_id'],
            },
        ),
        migrations.CreateModel(
            name='MedicineDispensation',
            fields=[
                ('dispensation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(db_index=True, help_text='Opaque student identifier owned by Registrar', max_length=100)),
                ('medicine_id', models.CharField(db_index=True, help_text='Opaque medicine identifier owned by Inventory', max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ROLLED_BACK', 'Rolled Back')], default='COMPLETED', max_length=20)),
                ('inventory_transaction_id', models.CharField(blank=True, db_index=True, default='', help_text='Inventory transaction created when stock is deducted', max_length=100)),
                ('rollback_transaction_id', models.CharField(blank=True, help_text='Inventory transaction created when a dispensation is rolled back', max_length=100, null=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicine_dispensations',
                'ordering': ['-dispensed_at', '-dispensation_id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_name',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_course_sec',
        ),
        migrations.RemoveIndex(
            model_name='healthrecord',
            name='idx_hr_student_visit',
        ),
        migrations.RemoveIndex(
            model_name='healthrecord',
            name='idx_hr_visit',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='current_medications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='medical_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['student_id', '-consulted_at'], name='idx_cons_student_date'),
        ),
        migrations.AddIndex(
            model_name='healthstatus',
            index=models.Index(fields=['student_id', '-effective_at'], name='idx_hs_student_effect'),
        ),
        migrations.AddIndex(
            model_name='healthstatus',
            index=models.Index(fields=['status'], name='idx_hs_status'),
        ),
        migrations.AddIndex(
            model_name='medicinedispensation',
            index=models.Index(fields=['student_id', '-dispensed_at'], name='idx_md_student_date'),
        ),
        migrations.AddIndex(
            model_name='medicinedispensation',
            index=models.Index(fields=['medicine_id', '-dispensed_at'], name='idx_md_medicine_date'),
        ),
        migrations.AddIndex(
            model_name='medicinedispensation',
            index=models.Index(fields=['status'], name='idx_md_status'),
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='health_id',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='health_record_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-created_at', '-health_record_id']},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='student',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='student_id',
            field=models.CharField(
                db_index=True,
                help_text='Opaque student identifier owned by Registrar',
                max_length=100,
                null=True),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['student_id', '-created_at'],
            name='idx_hr_student_created'),
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='weight',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
