# Generated by Django 6.1.1 on 2026-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_canonical_clinic_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='student_id',
            field=models.CharField(db_index=True, help_text='Opaque student identifier owned by Registrar', max_length=100),
        ),
    ]
