# Generated by Django 6.1.1 on 2026-09-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_enforce_healthrecord_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='height',
        ),
    ]
